# Generated by Django 2.2 on 2021-04-24 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inv', '0003_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('numero_documento', models.IntegerField(default=0)),
                ('numero_viaje', models.IntegerField(default=0)),
                ('fecha_recepcion', models.DateField(blank=True, null=True)),
                ('hora_recepcion', models.DateField(blank=True, null=True)),
                ('ubicacion', models.CharField(max_length=200)),
                ('inicial', models.IntegerField(default=0)),
                ('final', models.IntegerField(default=0)),
                ('litros_recibidos', models.IntegerField(default=0)),
                ('diferencia', models.IntegerField(default=0)),
                ('tk', models.IntegerField(default=0)),
                ('temperatura', models.IntegerField(default=0)),
                ('api', models.FloatField(default=0)),
                ('descripcion', models.CharField(max_length=200)),
                ('subCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.SubCategoria')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
