# Generated by Django 2.2 on 2021-04-27 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0004_bitacora'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bitacora',
            options={'verbose_name_plural': 'Bitacoras'},
        ),
    ]
