# Generated by Django 2.2 on 2021-06-03 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0006_delete_facturadet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacturaDetall',
        ),
    ]
