# Generated by Django 2.2 on 2021-06-03 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0008_facturadet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacturaDeta',
        ),
    ]
